Redesign.
ktustanowski/UnitTestApplication pull request #1
Opened 2017-02-05 18:40 UTC by ktustanowski

2017-02-05 20:05 UTC, dbacinski requested changes

2017-02-05 20:05 UTC, dbacinski commented on UnitTestApplicationTests/LoginViewControllerTests.swift
> +    func testThatLoginIsEmailValidatorIsSetOnViewDidLoad() {
test name should be reflected in assertions, I would give a better name, we don't care if validator is set or not but if controller gives expected result.

2017-02-05 20:05 UTC, dbacinski commented on UnitTestApplicationTests/LoginViewControllerTests.swift
> +        viewController.spinner.stopAnimating()
i guess that above attributes are not parameters of this test, I would extract them into method setupInitialState

2017-02-05 20:05 UTC, dbacinski commented on UnitTestApplicationTests/LoginViewControllerTests.swift
> +        viewController.spinner.stopAnimating()
just extract parameters that are not relevant for this test

2017-02-05 20:05 UTC, dbacinski commented on UnitTestApplicationTests/LoginViewControllerTests.swift
> +
remove redundant new lines

2017-02-10 21:49 UTC, ktustanowski commented on UnitTestApplicationTests/LoginViewControllerTests.swift
> +    func testThatLoginIsEmailValidatorIsSetOnViewDidLoad() {
I was thinking about this and in this case I actually want to make sure that all validators are set and present - and the way I'm checking it is by calling sign in (thanks to your advice). This assertions are saying - this is set. If this is not enormous flaw in your opinion I would leave this as is.

2017-02-11 06:49 UTC, dbacinski commented
+1 looks good to me

2017-02-11 06:49 UTC, dbacinski commented on UnitTestApplicationTests/LoginViewControllerTests.swift
> +    func testThatLoginIsEmailValidatorIsSetOnViewDidLoad() {
ok

2017-03-14 23:35 UTC, merged